---

- name: Haproxy role execution
  hosts: proxy
  become: true
  roles:
    - role: geerlingguy.haproxy
      vars:
        haproxy_backend_balance_method: roundrobin
        haproxy_backend_servers:
          - name: app1
            address: 10.0.15.27:80
          - name: app2
            address: 10.0.15.28:80
  tasks:
    - name: Ensure firewalld is installed
      yum:
        name: firewalld
        state: latest

    - name: Ensure firewalld is started and enabled
      service:
        name: firewalld
        state: started
        enabled: true

    - name: Ensure correct configuration on firewalld
      firewalld:
        port: 80/tcp
        state: enabled
        immediate: true
        permanent: true

...
