---

- name: Hosts play
  hosts: all
  become: true
  tasks:
    - name: Transfer template file to the remote location
      template:
        src: templates/hosts.j2
        dest: /etc/hosts
        mode: 0644
        owner: root
        group: root

...
